project:
  type: website
  output-dir: docs
  resources:
    - files/photos/**

# Meta
description-meta: "Personal academic website for Ziqian Xia"
author-meta: "Ziqian Xia"

website:
  title: "Ziqian Xia"
  image: "https://quarto.org/quarto.png"
  description: "Personal academic website for Ziqian Xia"
  favicon: Stanford_Cardinal_logo.svg  
  google-analytics: "G-2BKT478GNZ"

  navbar:
    background: light 
    logo: files/images/stanford-logo2.png   # <- drop your Stanford logo here (PNG/SVG), adjust path/name as needed
    left:
      - text: About
        menu:
          - text: Contact
            href: contact.qmd
      - text: Research
        menu:
          - text: Publications
            href: publications.qmd
      - text: Resources
        menu:
          - text: Software
            href: Software.qmd
          - text: Mentorship Notes
            href: mentorship-notes.qmd
      - text: Personal
        href: personal-album.qmd
      - text: News
        href: news.qmd 
    right:
      - text: CV
        href: files/CV-Ziqian.pdf
      - icon: github
        href: https://github.com/ziqian-xia
        target: _blank

  page-navigation: true

  page-footer:
    left: "[Ziqian Xia](https://github.com/ziqian-xia) © <script>document.write(new Date().getFullYear())</script>"
    center: "Built with Quarto • Stanford Doerr School of Sustainability"
    right:
      - icon: github
        href: https://github.com/drganghe/quarto-academic-website-template
        target: _blank


  search:
    location: navbar
    type: textbox

  reader-mode: true
  draft-mode: unlinked
  repo-url: https://github.com/Ziqian-xia/blog2025
  open-graph: true
  twitter-card: true
  site-url: "https://ziqian-xia.github.io/blog2025"

bibliography: references.bib


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    include-in-header: "files/includes/_academic.qmd"

execute:
  freeze: auto
